CREATE TABLE Developer(
   Developer_ID   VARCHAR(50) NOT NULL PRIMARY KEY
  ,Developer_Name VARCHAR(1700) NOT NULL
  ,Website        VARCHAR(2000) NOT NULL
  ,Country        VARCHAR(3600) NOT NULL
);
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0001','AceFixers','AceFixers.com','El Salvador');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0002','AdDirectors','AdDirectors.com','Ecuador');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0003','AfricanClay','AfricanClay.com','Estonia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0004','AltTutors','AltTutors.com','Curacao');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0005','America''sVictory','AmericaVictory.com','Jersey');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0006','ArtPrintings','ArtPrintings.com','Mexico');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0007','AskHowToDo','Ahtd.com','Morocco');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0008','AtopStudio','AtopStudio.com','Guam');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0009','AudioBookAccess','AbAccess.com','Libya');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0010','BeSourceful','BeSourceful.com','Canada');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0011','BestYouths','BestYouths.com','Saint Barthelemy');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0012','BeyondCollege','Beyondclg.com','Benin');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0013','BookingBargain','BookingBargain.com','Iran');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0014','BoxingFaq','Boxingfaq.com','New Zealand');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0015','CaptionChallenge','CaptionChallenge.com','Finland');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0016','CarRentalMunich','Thecrm.com','Niger');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0017','CatOnEarth','CatOnEarth.com','Democratic Republic of the Congo');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0018','CentralCoupons','CentralCoupons.com','Senegal');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0019','ChilMixer','ChilMixer.com','Niue');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0020','ComeToMilan.','MilanTCDot.com','Svalbard and Jan Mayen');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0021','ComingToLondon','ComingToLondon.com','Serbia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0022','CosyTheme','CosyTheme.com','Bangladesh');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0023','CrashGirl','CrashGirl.com','Honduras');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0024','CreatesIncome','CreatesIncome.com','Burundi');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0025','CunningCat','CunningCat.com','Norway');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0026','CutiePage','CutiePage.com','Namibia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0027','DeveloperHeaven','DeveloperHeaven.com','Israel');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0028','DiplomaticStatus','DiplomaticStatus.com','Antigua and Barbuda');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0029','DutchGates','DutchGates.com','Algeria');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0030','EmptyCarts','EmptyCarts.com','Afghanistan');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0031','FancyLittle','FancyLittle.com','Nepal');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0032','FatWalker.','FWDot.com','Heard Island and McDonald Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0033','FemaleMate','FemaleMate.com','Puerto Rico');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0034','FilmReviewers','FilmReviewers.com','Panama');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0035','FishingKiosk','FishingKiosk.com','Swaziland');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0036','FixAlarm','FixAlarm.com','Iceland');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0037','FlashTalents','FlashTalents.com','Sweden');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0038','FleshMannequins','FleshMannequins.com','Hungary');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0039','FloralTheme','FloralTheme.com','U.S. Virgin Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0040','FriedStone','FriedStone.com','Burkina Faso');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0041','GagdetsList','GadgetsList.com','Greenland');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0042','GetOilPaintings','GetOilPaintings.com','Sao Tome and Principe');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0043','GetYoureBuisness','Getyourbusiness.com','Christmas Island');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0044','Gobula','Gobula.com','Gibraltar');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0045','GreatNobles','GreatNobles.com','Isle of Man');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0046','HalloAmerika','HalloAmerika.com','Senegal');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0047','HealthcareExtra','HealthcareExtra.com','Estonia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0048','HouseboatEurope','HouseboatEurope.com','Venezuela');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0049','HouseOfCultures','HouseOfCultures.com','Sudan');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0050','HowTheyRank','HowTheyRank.com','Kyrgyzstan');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0051','HunkSta','HunkSta.com','Monaco');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0052','HutZone','HutZone.com','Niger');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0053','Hyetal','Hyetal.com','Tunisia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0054','IdiotGuys','IdiotGuys.com','Monaco');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0055','InfoForMarketing','InfoForMarketing.com','Brunei');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0056','InsightPsychics','InsightPsychics.com','Guinea');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0057','InsightsFrance','InsightsFrance.com','New Zealand');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0058','InstepDesigns','InstepDesigns.com','Palau');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0059','ItProvides','ItProvides.com','United Arab Emirates');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0060','JaguarShowroom','JaguarShowroom.com','Honduras');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0061','JizzyBoys','JizzyBoys.com','Gabon');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0062','KeyboardStuff','KeyboardStuff.com','Swaziland');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0063','KeyDigits','KeyDigits.com','Bhutan');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0064','KickbackDeal','KickbackDeal.com','Cocos Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0065','KingTots','KingTots.com','Falkland Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0066','LatestDailyDeals','LatestDailyDeals.com','Isle of Man');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0067','LearnToImport','LearnToImport.com','Jersey');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0068','LegendGlow','LegendGlow.com','Norfolk Island');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0069','LetRoid','LetRoid.com','Burundi');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0070','LetsVisitParis','LetsVisitParis.com','United Kingdom');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0071','LetsWorkOutside','LetsWorkOutside.com','Afghanistan');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0072','LillyKit','LillyKit.com','Niue');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0073','LinuxConfigure','LinuxConfigure.com','Niger');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0074','LiquidAloeVera','LiquidAloeVera.com','Cocos Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0075','LiquidInks','LiquidInks.com','Ghana');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0076','LongDeepBreath','LongDeepBreath.com','Tunisia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0077','LoveForNail','LoveForNail.com','El Salvador');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0078','LoverHugs','LoverHugs.com','Niue');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0079','MakingOfDesign.','MakingofDesign.com','Tuvalu');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0080','MaryMacLean','MaryMclean.com','Gambia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0081','MatLady','MatLady.com','Bangladesh');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0082','MeasureWaist','MeasureWaist.com','Gibraltar');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0083','MenCounters','MenCounters.com','Svalbard and Jan Mayen');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0084','Minopia','Minopia.com','Malawi');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0085','MissJunk','MissJunk.com','Montenegro');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0086','MotivationalRock.','MotivationalRock.com','French Polynesia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0087','MovieSearchin','MovieSearching.com','Benin');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0088','MusicSparkl','MusicSparkle.com','Macao');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0089','MyFastProfits','MyFastProfits.com','Democratic Republic of the Congo');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0090','MyLocalSources','MyLocalSources.com','Cook Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0091','NationalparkList','NationalParkList.com','Benin');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0092','NewExtentIons','NewExtentIons.com','El Salvador');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0093','NewLocalGirls','NewLocalGirls.com','Iran');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0094','Odessay','Odessay.com','Niger');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0095','OkDude','OkDudes.com','Saint Martin');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0096','OliveFlow.','OliveFlow.com','Gibraltar');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0097','OneAstrology','OneAstrology.com','Guinea');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0098','OneYearPast','OneYearPast.com','Western Sahara');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0099','OnlineCashKey','OnlineCashKey.com','Christmas Island');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0100','OnlyForBridal','OnlyForBridal.com','Russia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0101','OnPressRelease','OnPressRelease.com','Sao Tome and Principe');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0102','PaperToyGift','PaperToyGift.com','Falkland Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0103','ParkTheDomain','ParkTheDomain.com','Malawi');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0104','PizzaBurning','PizzaBurning.com','Canada');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0105','PullingPictures','PullingPictures.com','United States');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0106','RankPusher','RankPusher.com','Zimbabwe');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0107','Ravepen','RavePen.com','United States Minor Outlying Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0108','RaversHeaven','RaversHeaven.com','Canada');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0109','RedMessages','RedMessages.com','Estonia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0110','RememberGuide','RememberGuide.com','Gibraltar');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0111','RichAndCrystal','RichCrystal.com','Bulgaria');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0112','RiskyTeens','RiskyTeens.com','Wallis and Futuna');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0113','SearchVan','SearchVan.com','Poland');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0114','SeductiveLace','SeductiveLace.com','United States');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0115','SellYourMovies','SellUrMovies.com','El Salvador');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0116','SevenHug','SevenHug.com','Gambia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0117','ShadesOfMakeup','ShadesOfMakeup.com','New Caledonia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0118','SilverJeans','SilverJeans.com','South Africa');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0119','SmartThingsToDo','SmartThingsToDo.com','Barbados');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0120','SonyCenters','SonyCentres.com','Honduras');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0121','SparkyLips','SparkyLips.com','Palau');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0122','SpecialCarTuning','SpecialCarTuning.com','Armenia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0123','StarMoka','StarMoka.com','Mexico');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0124','StockmarketHints','StockMarketHints.com','Ghana');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0125','StrikeFresh','StrikeFresh.com','Bulgaria');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0126','StuffedEmotions','StuffedEmotions.com','Bahamas');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0127','StunningMan','StunningMan.com','Jersey');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0128','SuccessRays','SuccessRays.com','Georgia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0129','SuperMustangs','SuperMustangs.com','Isle of Man');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0130','TalentedCareers','TalentedCareers.com','South Africa');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0131','TenPoll','TenPoll.com','Iran');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0132','TestGender','TestGender.com','Bonaire, Saint Eustatius and Saba');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0133','TheChildOfGod','TheChildOfGod.com','Benin');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0134','TheePlumber','TheePlumber.com','Norway');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0135','TheLittleLamp','TheLittleLamp.com','Guernsey');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0136','TheMuralArtist','TheMuralArtist.com','Bosnia and Herzegovina');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0137','ThePublicAffair','ThePublicAffair.com','Kiribati');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0138','TheSecretKeys','TheSecretKeys.com','U.S. Virgin Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0139','TheSixthHour','TheSixHour.com','Burkina Faso');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0140','TheTaxFiling','TheTaxFiling.com','Guernsey');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0141','ThirtySingles','ThreeZeroSingles.com','Portugal');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0142','TingleHood','TingleHood.com','Bulgaria');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0143','TradeTransact','TradeTransact.com','Antigua and Barbuda');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0144','TravelersRights','TravelersRights.com','Faroe Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0145','TwinkLees','Twinklees.com','Bahrain');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0146','TwinParrot','TwinParrot.com','Svalbard and Jan Mayen');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0147','UnderTheBanner','UnderTheBanner.com','El Salvador');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0148','UponDrinks','UponDrinks.com','Yemen');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0149','ValuesShop','Valueshop.com','Isle of Man');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0150','VeryChubby','VeryChubby.com','India');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0151','VeryHappyEndings','VeryHappyEndings.com','United States Of America');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0152','VikingBuffet','VikingBuffet.com','England');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0153','VisualAppBuilder','VisualAppBuilder.com','Palestinian Islands');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0154','WholesaleMarts','WholesaleMarts.com','Bangladesh');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0155','WorldCenterpoint','WorldCenter.com','Myanmar');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0156','YesRite','YesRite.com','Indonesia');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0157','ZenTop','ZenTop.com','Haiti');
INSERT INTO Developer(Developer_ID,Developer_Name,Website,Country) VALUES ('D0158','NoMoreGods','nmg.com','United Kingdom');
