CREATE TABLE GAMES(
   App_Name         VARCHAR(4000) NOT NULL
  ,App_ID           INTEGER  PRIMARY KEY 
  ,Genre            VARCHAR(2900)
  ,Age_Requirements VARCHAR(1400) NOT NULL
);
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DJMAX TECHNIKA Q - Music Game',3,'Music','Content Rating');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Super Mario Run',4,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('RULES OF SURVIVAL',16,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Mupen64Plus AE (N64 Emulator)',37,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('8 Ball Pool',39,'Sports','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rush',40,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Super Jim Jump - pixel 3d',56,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Alto''s Adventure',65,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Mad Skills BMX 2',76,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Flow Free',84,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Law of Creation: A Playable Manga',98,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Star Wars',102,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Subway Surfers',109,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Tsunami',115,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('ROBLOX',117,'Adventure;Action & Adventure','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('RULES OF SURVIVAL',138,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('slither.io',139,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Jewels classic Prince',144,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Geometry Dash World',152,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cops N Robbers 2',172,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Looper!',173,'Puzzle','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cooking Fever',177,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cheating Tom 3 - Genius School',185,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Hunter: Post Apocalypse Survival Games',201,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Word Link',207,'Word','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Castle Clash: Heroes of the Empire US',216,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Game of Thrones: Conquestâ„¢',220,'Strategy','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Roll the BallÂ® - slide puzzle',223,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Maze Runner',227,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Five Nights at Freddy''s 3 Demo',232,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Saga',257,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dragon X Adventure: Warrior Z',263,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('slither.io',271,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bubble Witch 3 Saga',279,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Crisis Action: 2018 NO.1 FPS',287,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Piano Tiles 2â„¢',290,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Magic Tiles - TWICE Edition (K-Pop)',313,'Music','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Geometry Dash Meltdown',315,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE 3D MOTOR :Racing Games Free',317,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Subway Surfers',324,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('8 Ball Pool',334,'Sports','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AH-1 Viper Cobra Ops - helicopter flight simulator',343,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Kick the Buddy',346,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dude Perfect 2',348,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Iron Blade',361,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Mobile Legends: Bang Bang',375,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Five Nights at Freddy''s',381,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rivals at War: Firefight',386,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Shadow Fight 2',398,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cyborg AX-001',410,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cops N Robbers',411,'Adventure','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Catchers',417,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Saga',418,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Draw a Stickman: EPIC 2 Free',421,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Oddworld: New ''n'' Tasty',425,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AXE.IO - Brutal Survival Battleground',428,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Clash of Clans',435,'Strategy','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('FINAL FANTASY BRAVE EXVIUS',438,'Role Playing','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Shooting King',447,'Sports','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Evil Apples: A Dirty Card Game',452,'Word','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('MARVEL Strike Force',458,'Role Playing','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Pixel Art: Color by Number Game',459,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rage Z: Multiplayer Zombie FPS Online Shooter',464,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('7 Nights at Pixel Pizzeria - 2',474,'Adventure','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Partymasters - Fun Idle Game',480,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Block Craft 3D: Building Simulator Games For Free',482,'Simulation','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Color by Number â€“ New Coloring Book',489,'Board','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Harry Potter: Hogwarts Mystery',498,'Adventure','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Strawberry Shortcake BerryRush',500,'Action;Action & Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Korean Dungeon: K-Word 1000',529,'Word','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Reload: The Z-Team',535,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('PAC-MAN',539,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sniper 3D Gun Shooter: Free Shooting Games - FPS',547,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('THE KING OF FIGHTERS-A 2012(F)',553,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE 3D Moto 3',568,'Racing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Last Shelter: Survival',569,'Strategy','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Axe Champion',581,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Galaxy Attack: Alien Shooter',594,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('BEYBLADE BURST app',595,'Action;Action & Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Five Nights at Freddy''s 3',602,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Granny',607,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Monument Valley 2',613,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('PUBG MOBILE',616,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Guns of Boom - Online Shooter',623,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('UNO â„¢ & Friends',624,'Card','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The World Ends With You',636,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('4 in a Row',656,'Board','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Doodle Jump',659,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('GUNSHIP BATTLE: Helicopter 3D',668,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('PokÃ©mon GO',670,'Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hello Kitty Nail Salon',683,'Casual;Pretend Play','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('STARDOM: THE A-LIST',686,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('slither.io',687,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Pacific Navy Fighter C.E. (AS)',689,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Guns Royale - Multiplayer Blocky Battle Royale',693,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Helix Jump',717,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cash, Inc. Money Clicker Game & Business Adventure',725,'Simulation','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('War and Order',751,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Catchers',755,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fishdom',756,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('MLB TAP SPORTS BASEBALL 2018',763,'Sports','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('MARVEL Strike Force',785,'Role Playing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Smash Hit',788,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Assassin''s Creed Identity',790,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('My Boy! Free - GBA Emulator',806,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('GALAK-Z: Variant Mobile',820,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Catchers',827,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Traffic Racer',828,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DRAGON BALL LEGENDS',857,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rider',876,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Race the Traffic Moto',885,'Racing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Call of DutyÂ®: Heroes',905,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Swamp Attack',919,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Word Search',928,'Word','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('â–º MultiCraft â€• Free Miner! ðŸ‘',933,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bowmasters',939,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Stack Jump',953,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('PUBG MOBILE',955,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Jetpack Joyride',983,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Tank Stars',984,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Four In A Line Free',1024,'Board','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Episode - Choose Your Story',1030,'Simulation','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('My Talking Tom',1033,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ay Vamos - PJ. Balvin - Piano',1040,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Magic Tiles 3',1057,'Music','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('BC Slots - The Lost Reels FREE',1072,'Casino','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Gems or jewels ?',1084,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Mupen64+AE FREE (N64 Emulator)',1094,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Toon Blast',1102,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Helix Jump',1109,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('CURSUM B',1119,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('KIM KARDASHIAN: HOLLYWOOD',1120,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Run Sausage Run!',1129,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Avatar Musik',1136,'Music','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fishdom',1145,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Draw In',1154,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cut the Rope FULL FREE',1165,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fruit Block - Puzzle Legend',1179,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Super Dancer VN',1186,'Music','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hello Stars',1199,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Clash Royale',1203,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Magic Tiles 3',1209,'Music','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ant Smasher by Best Cool & Fun Games',1215,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds 2',1224,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('U-48 Submarine Commander Free',1225,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Color Road',1227,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bubble Shooter',1231,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Helix Jump',1234,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Score! Hero',1241,'Sports','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Avengers:(Dreamsky)Stickman War Z',1246,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dream League Soccer 2018',1249,'Sports','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fate/Grand Order (English)',1253,'Role Playing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Axe Throw: Flip Champ Axes Champion Throwing Games',1270,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Honkai Impact 3rd',1279,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dragon Hills',1288,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Gang Sniper V. Pocket Edition.',1295,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sonic Dash',1298,'Arcade','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Axe Champs! Wars',1300,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Stack It AR',1311,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Summoners War',1338,'Role Playing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Mad Day - Truck Distance Game',1352,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DINO HUNTER: DEADLY SHORES',1358,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Jelly Saga',1375,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Undead Assault',1385,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Battlelands Royale',1392,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ra Ga Ba',1402,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fruits Bomb',1403,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AG Drive 3D',1413,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Video Poker',1417,'Casino','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('I Am Innocent',1424,'Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Mafia City',1431,'Strategy','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Space X: Sky Wars of Air Force',1441,'Arcade','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bubble Shooter 2',1444,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Call of Duty:Black Ops Zombies',1447,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Soda Saga',1455,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('V for Voodoo',1477,'Trivia','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Word Search',1490,'Word','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Power Rangers Dino Charge',1497,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Vikings: an Archer''s Journey',1513,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('San Andreas: Gang Crime V',1530,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('PUBG MOBILE',1535,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Don''t Starve: Shipwrecked',1537,'Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Don''t Starve: Pocket Edition',1547,'Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Marble Woka Woka 2018 - Bubble Shooter Match 3',1576,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('X-WOLF',1577,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Super Jabber Jump 3',1582,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Star Wars â„¢: DIRTY',1620,'Role Playing','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Coin Mania : Arcade Fun',1643,'Casino','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('1LINE â€“ One Line with One Touch',1644,'Board','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hungry Shark Evolution',1652,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hole.io',1686,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Love Dance',1709,'Music','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('R-TYPE',1715,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Solitaire TriPeaks',1753,'Card','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bricks n Balls',1762,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Four In A Line',1763,'Board','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rope Hero Return of a Legend',1773,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('MARVEL Contest of Champions',1774,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Plants vs. Zombies FREE',1776,'Strategy','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Clash Royale',1794,'Strategy','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Trivia Crack',1799,'Trivia','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Jewels Star: OZ adventure',1802,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fallout Shelter',1823,'Simulation','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Soda Saga',1837,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Choices: Stories You Play',1855,'Simulation','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Robocar X Ray',1859,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Extreme Car Driving Simulator',1875,'Racing','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hill Climb Racing',1890,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('PokÃ©mon GO',1906,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Stupid Zombies',1912,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Will it Crush?',1922,'Simulation','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Master Moto',1928,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Mini DAYZ: Zombie Survival',1929,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Minion Rush: Despicable Me Official Game',1940,'Casual;Action & Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Quiz: Logo game',1943,'Trivia','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Word Search',1952,'Word','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Tsunami',1954,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Guess the song of J Balvin',1956,'Trivia','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Gun Strike Shoot',1960,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('SHADOWGUN LEGENDS',1982,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Room: Old Sins',1985,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Anger of stick 5 : zombie',1992,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Rio',2004,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Tokyo Ghoul: Dark War',2009,'Role Playing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Subway Surfers',2010,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Pou',2022,'Casual','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bowmasters',2037,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rock N'' Cash Casino Slots -Free Vegas Slot Games',2038,'Casino','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Car Driving Simulator Drift',2053,'Racing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Block Puzzle',2060,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Score! Hero',2061,'Sports','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Temple Run 2',2069,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Cube',2077,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Block Craft 3D: Building Simulator Games For Free',2078,'Simulation','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Swamp Attack',2089,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Classic',2109,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Critical Ops',2111,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AK-47 Assult Rifle: Gun Shooting Simulator Game',2131,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('B-52 Spirits of Glory Deluxe',2152,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dungeon Hunter Champions: Epic Online Action RPG',2154,'Role Playing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hill Climb Racing',2176,'Racing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Anger of stick 5 : zombie',2177,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('San Andreas Crime Stories',2180,'Racing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('J Balvin Piano Tiles',2181,'Music','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('CATS: Crash Arena Turbo Stars',2186,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Axe Knight',2189,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Talking Tom Gold Run',2190,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('B-Grade Renegade',2191,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Helix',2196,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Mental Hospital V',2197,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Flow Free',2226,'Puzzle','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Jurassic Worldâ„¢ Alive',2229,'Simulation','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('8 Ball Pool',2242,'Sports','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cops N Robbers - FPS Mini Game',2263,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Nightenfell: Shared AR',2269,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Block Puzzle Classic Legend !',2270,'Puzzle','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DRAGON BALL Z DOKKAN BATTLE',2276,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Don''t Hug Me I''m So Scared',2279,'Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Walking Dead: Our World',2280,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE FreeCell',2288,'Card','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Solitaire',2290,'Card','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Classic',2291,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('RC City Police Heavy Traffic Racer',2297,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('My Talking Tom',2340,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fishdom',2353,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Five Nights at Flappy''s',2354,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Auction Wars : Storage King',2373,'Casino','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Clash of Axe: Flippy Lumberjack Action X',2384,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Nights at Cube Pizzeria 3D â€“ 4',2397,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Helix Jump',2408,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Temple Run 2',2415,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Shoot Strike War Fire',2431,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Jump''N''Shoot Attack',2439,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hustle Castle: Fantasy Kingdom',2456,'Role Playing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Galaxy Attack: Alien Shooter',2465,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sonic the Hedgehogâ„¢ Classic',2467,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Tsunami',2469,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Farming Simulator 18',2489,'Simulation;Education','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Agar.io',2507,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Clue',2508,'Board','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Vikings',2517,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cooking Fever',2528,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bubble Shooter Space',2545,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('MORTAL KOMBAT X',2554,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Magic Tiles 3',2560,'Music','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('FRONTLINE COMMANDO: D-DAY',2563,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Strange Hero: Future Battle',2565,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Pou',2575,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Words With Friends Classic',2578,'Word','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('8 Ball Pool',2585,'Sports','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Asphalt 8: Airborne',2587,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Walking Dead: Road to Survival',2590,'Role Playing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Saga',2601,'Casual','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Temple Run 2',2611,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('YAKALA AY',2615,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Arena of Valor: 5v5 Arena Game',2638,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Blossom Blast Saga',2639,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Escapists',2642,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Super Jim Jump - pixel 3d',2643,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Fishing Hunter',2644,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Kick the Buddy',2657,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('PAC-MAN',2663,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Two Nights at jumpscare',2665,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rider',2669,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Solitaire',2670,'Card','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Classic',2678,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ghouls''n Ghosts MOBILE',2686,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Runner 3d like',2687,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rock n Roll Music Quiz Game',2697,'Trivia','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Au Mobile: Audition ChÃ­nh Hiá»‡u',2703,'Music','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Arrow.io',2706,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Baby Game Animal Jam Free',2709,'Board','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Radial-G : Infinity',2713,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bowmasters',2737,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Woodman Deluxe',2755,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Bingo: Offline Bingo Games',2765,'Casino','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Catchers',2771,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('G-Switch',2773,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cover Fire: offline shooting games for free',2774,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bubble Shooter 2',2778,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rolling G Sky',2780,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Girls'' Frontline',2782,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zlax.io Zombs Luv Ax',2785,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rolling Sky',2826,'Board','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Extreme Match',2828,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bubble Shooter',2831,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('G-Switch 2',2850,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sniper 3D Gun Shooter: Free Shooting Games - FPS',2871,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Game of Life',2913,'Board','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Talking Tom Gold Run',2925,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Super Dancer',2934,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Yes day',2945,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hungry Shark World',2946,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ghosts''n Goblins MOBILE',2948,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Saga',2956,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Temple Run 2',2964,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Master of Eternity(MOE)',2971,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Farm Heroes Saga',2986,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ingress',2989,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AK-47 3D',3007,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('PUBG MOBILE',3008,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Block Battles: Heroes at War - Multiplayer PVP',3011,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Garena Free Fire',3027,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DEAD TARGET: FPS Zombie Apocalypse Survival Games',3047,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Real City Car Driver',3056,'Racing','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Merge Dragons!',3058,'Puzzle','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bubble Shooter',3067,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('TerraGenesis - Space Colony',3077,'Simulation','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Nights at Cube Pizzeria 3D â€“ 2',3078,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Gangster Town',3087,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Axe Champ',3090,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Granny',3100,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Solitaire!',3102,'Card','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Rio',3119,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('M-acceleration 3D Car Racing',3123,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Jewels 2: Island Adventures',3132,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Solitaire: Decked Out Ad Free',3133,'Card','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('War Robots',3158,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hill Climb Racing',3166,'Racing','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Earn to Die 2',3167,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE GTO Racing',3179,'Racing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Magic Tiles 3',3189,'Music','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Flip the Gun - Simulator Game',3193,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Grand Stickman Cover V',3199,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ao Oni2',3201,'Adventure','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Alto''s Adventure',3205,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('My Talking Angela',3206,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Offroad Outlaws',3207,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Motorbike Driving Simulator 3D',3215,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Plants vs. Zombies FREE',3221,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Five Nights at Freddy''s 4 Demo',3228,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sonic Dash',3236,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Granny',3258,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Draw a Stickman: EPIC Free',3262,'Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Marble - Temple Quest',3265,'Puzzle','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Jetpack Joyride',3267,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('4 in a row',3271,'Board','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Experiment Z - Zombie',3276,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Magic Tiles - Blackpink Edition (K-Pop)',3279,'Music','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('D Day World War II Commando Survival Shooting',3280,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Lineage 2: Revolution',3287,'Role Playing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Saga',3301,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Identity V',3311,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Glow Hockey',3313,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Temple Run 2',3326,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hopeless Land: Fight for Survival',3341,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('D+H Reaction Wall',3359,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('New YAHTZEEÂ® With Buddies Dice Game',3371,'Board','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('slither.io',3375,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Saga',3376,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Friends',3390,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Super Jim Jump - pixel 3d',3393,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Q*bert: Rebooted',3400,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('My Talking Angela',3402,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Jungle Marble Blast',3418,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Miraculous Ladybug & Cat Noir - The Official Game',3419,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dog Run - Pet Dog Simulator',3423,'Simulation;Action & Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AR Tank Battle',3429,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Fish Master!',3431,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Knife Hit',3437,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Flow Free',3439,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('I am Bread',3455,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Five Nights at Freddy''s 4',3463,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Blackjack aj Poker',3469,'Card','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Talking Tom Gold Run',3479,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Geometry Dash Lite',3483,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Gardenscapes',3484,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Granny',3490,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Disney Heroes: Battle Mode',3495,'Strategy','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Flat Pack',3502,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Crossy Road',3506,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Flippy Axe : Flip The Knife & Axe Simulator',3533,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Catchers',3542,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('ROBLOX',3563,'Adventure;Action & Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Pixel Art: Color by Number Game',3576,'Puzzle','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Stickman and Axe',3582,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Best Fiends - Free Puzzle Game',3593,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Block Puzzle',3604,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Baseball Boy!',3606,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sin City Crime Simulator V - Gangster',3608,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('My Talking Angela',3622,'Casual','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AU Mobile Indonesia',3628,'Music','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rope''n''Fly 4',3646,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fast like a Fox',3650,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Spider Solitaire',3656,'Card','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Heroes Arena',3669,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Guns of Glory',3675,'Strategy','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Tsunami',3712,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('NinJump',3730,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Soda Saga',3733,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Catchers',3791,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hero Fighter X',3824,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DEER HUNTER 2018',3830,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DEER HUNTER 2018',3833,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('ONScripter Plus (Ad Free)',3834,'Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('iSniper 3D Arctic Warfare',3838,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Pixel Art: Color by Number Game',3841,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Wordscapes',3842,'Word','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('VR AG Racing for Cardboard',3845,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('slither.io',3848,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ah! Coins',3858,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rolly Vortex',3861,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Draw A Stickman',3883,'Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('iGun Pro -The Original Gun App',3908,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hitman Sniper',3928,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Final Fantasy XV: A New Empire',3936,'Strategy','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Galaxy Attack: Alien Shooter',3948,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Grim Soul: Dark Fantasy Survival',3951,'Role Playing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DINO HUNTER: DEADLY SHORES',3952,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('slither.io',3964,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DRAGON BALL LEGENDS',3965,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Temple Run 2',3971,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hill Climb Racing 2',3972,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dead Zombie Evil Killer:Axe',3974,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Farm Heroes Saga',3981,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Tsunami',3988,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bowmasters',3998,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Draw Something Classic',4003,'Word','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Modern Action Commando 3D',4011,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Subway Surfers',4022,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE City Jump',4041,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Pou',4067,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Traffic Racer',4069,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hungry Shark Evolution',4077,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Racing in Car 2',4078,'Racing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Perfect Piano',4081,'Music','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('MMX Hill Dash 2 â€“ Offroad Truck, Car & Bike Racing',4088,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DEAD TARGET: FPS Zombie Apocalypse Survival Games',4099,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('5 Nights at Cube Pizzeria City',4134,'Adventure','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ghost Snap AR Horror Survival',4138,'Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('ROBLOX',4144,'Adventure;Action & Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie War Z : Hero Survival Rules',4145,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Clash Royale',4147,'Strategy','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Super Hero M Craft Run',4166,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Five Nights at Neighbor House',4171,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Draw N Guess Multiplayer',4174,'Word','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Merge Dragons!',4176,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Farm Heroes Saga',4184,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Word Search',4189,'Word','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Woody Puzzle',4194,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('R-TYPE II',4211,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hill Climb Racing',4232,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Beach Buggy Blitz',4239,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Extreme X Ray Robot Stunts',4246,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Traps n'' Gemstones',4257,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Granny',4270,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fruits Bomb',4272,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Blackjack',4275,'Card','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Counter Terrorist Attack',4311,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Paint Hit',4315,'Casual','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Axetatic - Axe Throwing Game',4322,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Garena Free Fire',4339,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Plants vs. Zombies FREE',4341,'Strategy','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Last Day on Earth: Survival',4344,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('G-Switch 3',4345,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Five Nights at Pizzeria',4348,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Major Mayhem',4363,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Stick War: Legacy',4364,'Strategy','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Mopar Drag N Brag',4370,'Racing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Soul Knight',4383,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Mini Golf King - Multiplayer Game',4390,'Sports','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Clash of Clans',4405,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bubble Shooter Genies',4431,'Casual','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Love Nikki-Dress UP Queen',4433,'Role Playing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('GUN ZOMBIE',4434,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fidget Spinner',4436,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Idle Heroes',4444,'Role Playing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Barbieâ„¢ Fashion Closet',4448,'Casual;Creativity','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Z Champions',4450,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rope''n''Fly 3 - Dusk Till Dawn',4453,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Toy Blast',4486,'Puzzle','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Garena Free Fire',4488,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cut the Rope FULL FREE',4493,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Harry Potter: Hogwarts Mystery',4543,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Drink-O-Tron The Drinking Game',4549,'Card','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hero Hunters',4556,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Wordscapes',4560,'Word','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AK Blackjack',4567,'Card','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Slendrina X',4572,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Crayola Color Blaster',4602,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Chapters: Interactive Stories',4635,'Role Playing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Love Balls',4644,'Puzzle','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Pixel Gun 3D: Survival shooter & Battle Royale',4648,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('diep.io',4671,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Honkai Impact 3rd',4678,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Axe Man',4680,'Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Gangstar Vegas - mafia game',4695,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Gun Shoot War Q',4706,'Arcade','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Rio',4723,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Vector',4731,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Five Nights at Freddy''s: SL',4732,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Guess the Class ðŸ”¥ AQW',4736,'Word','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Hunter King',4748,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AZ Rockets',4756,'Arcade','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Farm Heroes Saga',4757,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Go!',4761,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Banana Kong',4762,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dinosaur Simulator: Dino World',4774,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Hunter King',4778,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Jewels Legend - Match 3 Puzzle',4816,'Arcade','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('TEKKENâ„¢',4842,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Block Puzzle Classic Legend !',4847,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Wordscapes',4858,'Word','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dino T-Rex',4859,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ba Cristi',4862,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Angry Chef',4865,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Fruit NinjaÂ®',4876,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Lords Mobile: Battle of the Empires - Strategy RPG',4891,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Space Shooter : Galaxy Attack',4892,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Asylum Night Shift - Five Nights Survival',4896,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Miraculous Ladybug & Cat Noir - The Official Game',4915,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Carnivores: Dinosaur Hunter',4916,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Lep''s World ðŸ€',4936,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Arcraft - AR Sandbox',4942,'Adventure','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bus Rush: Subway Edition',4950,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Miami crime simulator',4952,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sniper 3D Gun Shooter: Free Shooting Games - FPS',4960,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Tiny Archers',4971,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Tomb of the Mask',4973,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Crossy Road',5030,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Obbligo o VeritÃ ? PRO',5032,'Board','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('SAMURAI vs ZOMBIES DEFENSE',5048,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Temple Run',5053,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Classic',5059,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Super Car F. Mod for MCPE',5071,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Farm Fruit Pop: Party Time',5073,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Gardenscapes',5092,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Pixel Z Gunner 3D - Battle Survival Fps',5100,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Who am I? (Biblical)',5109,'Trivia','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Word Crossy - A crossword game',5128,'Word','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cardi B Piano Game',5130,'Music','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ice Crush 2018 - A new Puzzle Matching Adventure',5143,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('RollerCoaster TycoonÂ® Classic',5157,'Simulation','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('M3-X5-X6-M-Ä°3-Ä°8 RACÄ°NG 2018',5162,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bowmasters',5170,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Real Gangster Crime',5194,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Helix Jump',5206,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Au-allstar for KR',5230,'Music','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Clash of Clans',5242,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('8 Ball Pool',5250,'Sports','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Simsâ„¢ FreePlay',5267,'Simulation','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Metal Soldiers 2',5286,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Flow Free',5305,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Casino X - Free Online Slots',5322,'Casino','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cube Z (Pixel Zombies)',5329,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Knife&Axe Throwing',5332,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('One Night at Golden Freddy''s',5343,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Hunter King',5347,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Agar.io',5358,'Action','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('PLANK!',5361,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Plants vs. Zombies FREE',5362,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hide N Seek : Mini Game',5367,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Crime Wars S. Andreas',5391,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('What Am I? - Brain Teasers',5396,'Trivia','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Saiyan Z: Super SSJ Ultimate Combat',5423,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DC Super Hero Girlsâ„¢',5429,'Action;Action & Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Jewels Star: OZ adventure',5438,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('WithstandZ - Zombie Survival!',5446,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hill Climb Racing 2',5447,'Racing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Homescapes',5457,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Shoot Bubble - Fruit Splash',5460,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Power Pop Bubbles',5477,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ultimate Fighter Z',5480,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Score! Hero',5492,'Sports','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Drag''n''Boom',5495,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Kill Shot Bravo: Sniper FPS',5513,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('My OldBoy! Free - GBC Emulator',5525,'Arcade','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Bomb',5535,'Casual;Brain Games','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Jewels',5540,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Homescapes',5546,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Nights at Slender Pizzeria 3D',5563,'Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('8 Ball Pool',5593,'Sports','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Ludo - Don''t get angry',5613,'Board','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sniper 3D Gun Shooter: Free Shooting Games - FPS',5619,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bubble Shooter',5629,'Casual','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Rope Hero 3',5635,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Gun Ball: arcade ball games',5642,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('ROBLOX',5657,'Adventure;Action & Adventure','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Talking Tom Gold Run',5663,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Block Puzzle',5674,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Classic',5685,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Axe Champ Hit',5690,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Subway Surfers',5694,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Lep''s World 2 ðŸ€ðŸ€',5704,'Arcade','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Solitaire',5706,'Card','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Armored Warfare: Assault',5712,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Best Fiends - Free Puzzle Game',5714,'Casual','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('DRAGON BALL LEGENDS',5721,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Angry Birds Rio',5724,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Kick the Buddy',5725,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sweet Fruit Candy',5731,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AJ Jump: Animal Jam Kangaroos!',5747,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Helix Jump',5763,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('AE Lucky Fishing',5766,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('J-Stars Victory VS Guide',5776,'Action','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Candy Crush Jelly Saga',5792,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Lock ''n'' Roll Pro - Ad Free',5793,'Card','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sniper 3D Gun Shooter: Free Shooting Games - FPS',5812,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('The Q - Live Trivia Game Network',5814,'Trivia','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dr. Driving',5818,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Geometry Dash World',5828,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Zombie Hunter King',5830,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Vikings Stickman Axe Fighting',5836,'Arcade','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Wordscapes',5837,'Word','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Snake VS Block',5844,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Might & Magic: Elemental Guardians',5845,'Role Playing','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Â¡Ay Metro!',5850,'Arcade','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bubble Shooter',5856,'Casual','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Last Day on Earth: Survival',5863,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('ROBLOX',5871,'Adventure;Action & Adventure','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Toon Blast',5877,'Puzzle','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Hungry Shark Evolution',5880,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Puppy Shooting an AK-47: Platformer Zombie Game',5883,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Route Z',5909,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Toon Blast',5918,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Block Puzzle',5921,'Puzzle','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Cooking Madness - A Chef''s Restaurant Games',5940,'Arcade','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dream League Soccer 2018',5947,'Sports','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Dino War: Rise of Beasts',5948,'Strategy','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Toy Blast',5970,'Puzzle','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Bike Race Free - Top Motorcycle Racing Games',5986,'Racing','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Once Upon a Tower',5992,'Action','Everyone');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Sniper 3D Gun Shooter: Free Shooting Games - FPS',5993,'Action','Everyone 10+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Earn to Die 2',5999,'Racing','Mature 17+');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES ('Subway Surfers',6015,'Arcade','Teen');
INSERT INTO GAMES(App_Name,App_ID,Genre,Age_Requirements) VALUES (NULL,NULL,NULL,'Everyone 10+');
