CREATE TABLE Top_Charts(
   App_ID        INTEGER  NOT NULL PRIMARY KEY 
  ,App_Name      VARCHAR(1000) NOT NULL
  ,Business      VARCHAR(100) NOT NULL
  ,Education     VARCHAR(100) NOT NULL
  ,Entertainment VARCHAR(100) NOT NULL
);
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2500,'Archos File Manager','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2501,'join.me - Simple Meetings','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2502,'PewDiePie''s Tuber Simulator','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2503,'Calculator ++','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2504,'Comptia A+ 220-901 & 220-902','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2505,'Emo Ads Blocker Browser','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2506,'Teach Me Anatomy','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2507,'Agar.io','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2508,'Clue','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2509,'Tastely','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2510,'MyASUS - Service Center','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2511,'Talking Tom Cat','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2512,'Rainfall radar - weather','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2513,'Anthem BC Anywhere','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2514,'C Pattern Programs Free','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2515,'Simple - Better Banking','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2516,'UBA Mobile Banking','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2517,'The Vikings','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2518,'ZArchiver','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2519,'Cougar Dating Life : Date Older Women Sugar Mummy','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2520,'Visual Anatomy 2','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2521,'Qapital - Save Small. Live Large','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2522,'SCB EASY','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2523,'Farming Simulator 14','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2524,'Step By Step Hairstyles For Women','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2525,'ZipRealty Real Estate & Homes','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2526,'Home workouts - fat burning, abs, legs, arms,chest','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2527,'LIVE VIDEO TALK','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2528,'Cooking Fever','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2529,'Snapchat','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2530,'I LOVE PASTA','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2531,'TurboScan: scan documents and receipts in PDF','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2532,'Haircut Tutorials/Haircut Videos','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2533,'R. Physics Puzzle Game','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2534,'Netflix','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2535,'Grand Theft Auto V: The Manual','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2536,'Eat''n Park','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2537,'Soccer Star 2018 Top Leagues Â· MLS Soccer Games','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2538,'Weight Watchers Mobile','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2539,'Google+','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2540,'Apex Launcher','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2541,'SH Script Runner','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2542,'WPS Office - Word, Docs, PDF, Note, Slide & Sheet','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2543,'Jobs in Canada - Emplois au Canada','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2544,'ao','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2545,'Bubble Shooter Space','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2546,'Microsoft Word','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2547,'Fines of the State Traffic Safety Inspectorate are official: inspection, payment of fines','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2548,'Puzzle Alarm Clock â°','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2549,'Chat Kids - Chat Room For Kids','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2550,'Prism Pay Bills, Track Money, Personal Finance','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2551,'Home Security Camera WardenCam - reuse old phones','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2552,'J Dark Ice Substratum Theme','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2553,'AO-EVENT','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2554,'MORTAL KOMBAT X','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2555,'The PCH App','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2556,'W Box VMS','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2557,'Babbel â€“ Learn Languages','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2558,'Dog Licks Screen Wallpaper','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2559,'Just a Line - Draw Anywhere, with AR','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2560,'Magic Tiles 3','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2561,'Lotte Home Shopping LOTTE Homeshopping','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2562,'Headspace: Meditation & Mindfulness','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2563,'FRONTLINE COMMANDO: D-DAY','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2564,'My Photo Keyboard','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2565,'Strange Hero: Future Battle','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2566,'Live Girls Talk - Free Video Chat','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2567,'Invoice & Time Tracking - Zoho','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2568,'Unit Converter Pro','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2569,'Android P Stock Wallpapers','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2570,'My Claro Peru','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2571,'Entel','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2572,'YouCut - Video Editor & Video Maker, No Watermark','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2573,'Guns''n''Glory Zombies Premium','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2574,'I''m Ping Pong King :)','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2575,'Pou','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2576,'L.POINT - ì—˜í¬ì¸íŠ¸ [ í¬ì¸íŠ¸, ë©¤ë²„ì‹­, ì ë¦½, ì‚¬ìš©, ëª¨ë°”ì¼ ì¹´ë“œ, ì¿ í°, ë¡¯ë°]','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2577,'Ð Ð˜Ð ÐÐ¾Ð²Ð¾ÑÑ‚Ð¸','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2578,'Words With Friends Classic','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2579,'Movies by Flixster, with Rotten Tomatoes','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2580,'MEGA','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2581,'Pocket AC','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2582,'Digital Clock AW-7','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2583,'3D Color Pixel by Number - Sandbox Art Coloring','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2584,'Low Blood Pressure Symptoms','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2585,'8 Ball Pool','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2586,'Full Code - Emergency Medicine Simulation','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2587,'Asphalt 8: Airborne','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2588,'Mehmet Emin Ay Ä°lahileri','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2589,'Q Alerts: QAnon Drop Notifications, Research +++','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2590,'The Walking Dead: Road to Survival','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2591,'Bita and the Animals - Pelos Ares','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2592,'Urbanspoon Restaurant Reviews','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2593,'NSE Mobile Trading','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2594,'HelloTalk â€” Chat, Speak & Learn Foreign Languages','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2595,'Mackolik Live Results','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2596,'Pick Your Part Garage','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2597,'Snapchat','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2598,'Meditation Studio','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2599,'AC Remote for Carrier - NOW FREE','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2600,'GoodRx Drug Prices and Coupons','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2601,'Candy Crush Saga','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2602,'Rent.com Apartment Homes','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2603,'IMDb Movies & TV','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2604,'GPS Navigation & Offline Maps Sygic','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2605,'imo free video calls and chat','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2606,'Whist - Tinnitus Relief','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2607,'British Airways','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2608,'WhatsCall Free Global Phone Call App & Cheap Calls','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2609,'Viber Messenger','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2610,'Learn Java','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2611,'Temple Run 2','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2612,'SuperPhoto - Effects & Filters','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2613,'Quick PDF Scanner + OCR FREE','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2614,'GoPro (formerly Capture)','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2615,'YAKALA AY','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2616,'Nokia mobile support','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2617,'Zaatar w Zeit','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2618,'Weather Crave','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2619,'Hola Launcher- Theme,Wallpaper','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2620,'La Liga - Spanish Soccer League Official','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2621,'Q Avatar (Avatar Maker)','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2622,'Truth or Dare Pro','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2623,'theScore: Live Sports Scores, News, Stats & Videos','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2624,'Learn English Words Free','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2625,'Caller ID +','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2626,'tournaments and more.aj.2','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2627,'1800 Contacts - Lens Store','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2628,'Sweet mi - unlimited hunnam hunting blind date','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2629,'Intesa Sanpaolo Mobile','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2630,'Journal Club: Medicine','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2631,'95Live -SG#1 Live Streaming App','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2632,'Mercado Libre: Find your favorite brands','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2633,'FOX NOW - On Demand & Live TV','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2634,'DramaFever: Stream Asian Drama Shows & Movies','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2635,'Poynt','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2636,'RetailMeNot - Coupons, Deals & Discount Shopping','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2637,'Home Workout - No Equipment','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2638,'Arena of Valor: 5v5 Arena Game','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2639,'Blossom Blast Saga','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2640,'icon wallpaper dressupðŸ’žCocoPPa','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2641,'The Guardian','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2642,'The Escapists','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2643,'Super Jim Jump - pixel 3d','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2644,'AE Fishing Hunter','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2645,'PBS KIDS Video','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2646,'Boston AH','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2647,'myQ','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2648,'Ebates: Cash Back, Coupons, Rewards & Savings','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2649,'Hot or Not - Find someone right now','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2650,'ConnectLine','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2651,'Elmo Calls by Sesame Street','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2652,'Shopular: Coupons, Weekly Ads & Shopping Deals','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2653,'GO SMS Pro - Messenger, Free Themes, Emoji','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2654,'Pretty Makeup, Beauty Photo Editor & Snappy Camera','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2655,'A. O. Smith','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2656,'Quick PDF Scanner + OCR FREE','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2657,'Kick the Buddy','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2658,'Au Rubis les bijoutiers','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2659,'My Chakra Meditation','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2660,'Free TV series','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2661,'Spreaker Podcast Radio','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2662,'BBW Dating & Curvy Singles Chat- LargeFriends','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2663,'PAC-MAN','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2664,'ivi - movies and TV shows in HD','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2665,'Two Nights at jumpscare','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2666,'Talking Tom Cat 2','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2667,'Fever Care','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2668,'Free intellectual training game application |','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2669,'Rider','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2670,'Solitaire','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2671,'Learn C++','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2672,'OfferUp - Buy. Sell. Offer Up','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2673,'Shopkins World!','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2674,'Keyboard - wallpapers , photos','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2675,'HomeAway Vacation Rentals','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2676,'Postmates Food Delivery: Order Eats & Alcohol','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2677,'Dating White Girls','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2678,'Angry Birds Classic','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2679,'MX Player','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2680,'Mike V: Skateboard Party PRO','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2681,'Adventure Xpress','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2682,'My baby Piano','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2683,'Fantasy Football','N','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2684,'Quran Juz-30 - Mahad al Zahra','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2685,'Instagram','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2686,'Ghouls''n Ghosts MOBILE','N','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2687,'Runner 3d like','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2688,'Papumba Academy - Fun Learning For Kids','Y','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2689,'Castlight Mobile','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2690,'Easy Origami Ideas','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2691,'Black Wallpaper, AMOLED, Dark Background: Darkify','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2692,'Fuelio: Gas log & costs','Y','Y','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2693,'Interracial Match Dating App','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2694,'S Player - Lightest and Most Powerful Video Player','Y','N','N');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2695,'AJ Cam','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2696,'Basics of Orthopaedics','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2697,'Rock n Roll Music Quiz Game','N','Y','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2698,'Cool Reader','N','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2699,'YouCam Makeup - Magic Selfie Makeovers','Y','N','Y');
INSERT INTO Top_Charts(App_ID,App_Name,Business,Education,Entertainment) VALUES (2700,'Free Blood Pressure','N','N','Y');
